server: 
  port: 9001
spring: 
  application:  
    name: tensquare_friend-[path_3] #指定服务名
  datasource:  
    driverClassName: [driverName]
    url: [url]
    username: root
    password: 199461
  jpa: 
    database: MySQL
    show-sql: true
